/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WarrantyRouteImport } from './routes/warranty'
import { Route as TransformationsRouteImport } from './routes/transformations'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookRepairRouteImport } from './routes/book-repair'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RepairSamsungRouteImport } from './routes/repair.samsung'
import { Route as RepairMacbookRouteImport } from './routes/repair.macbook'
import { Route as RepairIphone16ProMaxRouteImport } from './routes/repair.iphone-16-pro-max'
import { Route as RepairIphone15ProMaxRouteImport } from './routes/repair.iphone-15-pro-max'
import { Route as RepairIphone14ProMaxRouteImport } from './routes/repair.iphone-14-pro-max'
import { Route as RepairIphone13ProMaxRouteImport } from './routes/repair.iphone-13-pro-max'
import { Route as RepairIpadRouteImport } from './routes/repair.ipad'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const WarrantyRoute = WarrantyRouteImport.update({
  id: '/warranty',
  path: '/warranty',
  getParentRoute: () => rootRouteImport,
} as any)
const TransformationsRoute = TransformationsRouteImport.update({
  id: '/transformations',
  path: '/transformations',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRepairRoute = BookRepairRouteImport.update({
  id: '/book-repair',
  path: '/book-repair',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RepairSamsungRoute = RepairSamsungRouteImport.update({
  id: '/repair/samsung',
  path: '/repair/samsung',
  getParentRoute: () => rootRouteImport,
} as any)
const RepairMacbookRoute = RepairMacbookRouteImport.update({
  id: '/repair/macbook',
  path: '/repair/macbook',
  getParentRoute: () => rootRouteImport,
} as any)
const RepairIphone16ProMaxRoute = RepairIphone16ProMaxRouteImport.update({
  id: '/repair/iphone-16-pro-max',
  path: '/repair/iphone-16-pro-max',
  getParentRoute: () => rootRouteImport,
} as any)
const RepairIphone15ProMaxRoute = RepairIphone15ProMaxRouteImport.update({
  id: '/repair/iphone-15-pro-max',
  path: '/repair/iphone-15-pro-max',
  getParentRoute: () => rootRouteImport,
} as any)
const RepairIphone14ProMaxRoute = RepairIphone14ProMaxRouteImport.update({
  id: '/repair/iphone-14-pro-max',
  path: '/repair/iphone-14-pro-max',
  getParentRoute: () => rootRouteImport,
} as any)
const RepairIphone13ProMaxRoute = RepairIphone13ProMaxRouteImport.update({
  id: '/repair/iphone-13-pro-max',
  path: '/repair/iphone-13-pro-max',
  getParentRoute: () => rootRouteImport,
} as any)
const RepairIpadRoute = RepairIpadRouteImport.update({
  id: '/repair/ipad',
  path: '/repair/ipad',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/book-repair': typeof BookRepairRoute
  '/contact': typeof ContactRoute
  '/locations': typeof LocationsRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRoute
  '/transformations': typeof TransformationsRoute
  '/warranty': typeof WarrantyRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/repair/ipad': typeof RepairIpadRoute
  '/repair/iphone-13-pro-max': typeof RepairIphone13ProMaxRoute
  '/repair/iphone-14-pro-max': typeof RepairIphone14ProMaxRoute
  '/repair/iphone-15-pro-max': typeof RepairIphone15ProMaxRoute
  '/repair/iphone-16-pro-max': typeof RepairIphone16ProMaxRoute
  '/repair/macbook': typeof RepairMacbookRoute
  '/repair/samsung': typeof RepairSamsungRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/book-repair': typeof BookRepairRoute
  '/contact': typeof ContactRoute
  '/locations': typeof LocationsRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRoute
  '/transformations': typeof TransformationsRoute
  '/warranty': typeof WarrantyRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/repair/ipad': typeof RepairIpadRoute
  '/repair/iphone-13-pro-max': typeof RepairIphone13ProMaxRoute
  '/repair/iphone-14-pro-max': typeof RepairIphone14ProMaxRoute
  '/repair/iphone-15-pro-max': typeof RepairIphone15ProMaxRoute
  '/repair/iphone-16-pro-max': typeof RepairIphone16ProMaxRoute
  '/repair/macbook': typeof RepairMacbookRoute
  '/repair/samsung': typeof RepairSamsungRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/book-repair': typeof BookRepairRoute
  '/contact': typeof ContactRoute
  '/locations': typeof LocationsRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRoute
  '/transformations': typeof TransformationsRoute
  '/warranty': typeof WarrantyRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/repair/ipad': typeof RepairIpadRoute
  '/repair/iphone-13-pro-max': typeof RepairIphone13ProMaxRoute
  '/repair/iphone-14-pro-max': typeof RepairIphone14ProMaxRoute
  '/repair/iphone-15-pro-max': typeof RepairIphone15ProMaxRoute
  '/repair/iphone-16-pro-max': typeof RepairIphone16ProMaxRoute
  '/repair/macbook': typeof RepairMacbookRoute
  '/repair/samsung': typeof RepairSamsungRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/book-repair'
    | '/contact'
    | '/locations'
    | '/reviews'
    | '/services'
    | '/transformations'
    | '/warranty'
    | '/blog/$slug'
    | '/repair/ipad'
    | '/repair/iphone-13-pro-max'
    | '/repair/iphone-14-pro-max'
    | '/repair/iphone-15-pro-max'
    | '/repair/iphone-16-pro-max'
    | '/repair/macbook'
    | '/repair/samsung'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/book-repair'
    | '/contact'
    | '/locations'
    | '/reviews'
    | '/services'
    | '/transformations'
    | '/warranty'
    | '/blog/$slug'
    | '/repair/ipad'
    | '/repair/iphone-13-pro-max'
    | '/repair/iphone-14-pro-max'
    | '/repair/iphone-15-pro-max'
    | '/repair/iphone-16-pro-max'
    | '/repair/macbook'
    | '/repair/samsung'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/book-repair'
    | '/contact'
    | '/locations'
    | '/reviews'
    | '/services'
    | '/transformations'
    | '/warranty'
    | '/blog/$slug'
    | '/repair/ipad'
    | '/repair/iphone-13-pro-max'
    | '/repair/iphone-14-pro-max'
    | '/repair/iphone-15-pro-max'
    | '/repair/iphone-16-pro-max'
    | '/repair/macbook'
    | '/repair/samsung'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRouteWithChildren
  BookRepairRoute: typeof BookRepairRoute
  ContactRoute: typeof ContactRoute
  LocationsRoute: typeof LocationsRoute
  ReviewsRoute: typeof ReviewsRoute
  ServicesRoute: typeof ServicesRoute
  TransformationsRoute: typeof TransformationsRoute
  WarrantyRoute: typeof WarrantyRoute
  RepairIpadRoute: typeof RepairIpadRoute
  RepairIphone13ProMaxRoute: typeof RepairIphone13ProMaxRoute
  RepairIphone14ProMaxRoute: typeof RepairIphone14ProMaxRoute
  RepairIphone15ProMaxRoute: typeof RepairIphone15ProMaxRoute
  RepairIphone16ProMaxRoute: typeof RepairIphone16ProMaxRoute
  RepairMacbookRoute: typeof RepairMacbookRoute
  RepairSamsungRoute: typeof RepairSamsungRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/warranty': {
      id: '/warranty'
      path: '/warranty'
      fullPath: '/warranty'
      preLoaderRoute: typeof WarrantyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transformations': {
      id: '/transformations'
      path: '/transformations'
      fullPath: '/transformations'
      preLoaderRoute: typeof TransformationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-repair': {
      id: '/book-repair'
      path: '/book-repair'
      fullPath: '/book-repair'
      preLoaderRoute: typeof BookRepairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repair/samsung': {
      id: '/repair/samsung'
      path: '/repair/samsung'
      fullPath: '/repair/samsung'
      preLoaderRoute: typeof RepairSamsungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repair/macbook': {
      id: '/repair/macbook'
      path: '/repair/macbook'
      fullPath: '/repair/macbook'
      preLoaderRoute: typeof RepairMacbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repair/iphone-16-pro-max': {
      id: '/repair/iphone-16-pro-max'
      path: '/repair/iphone-16-pro-max'
      fullPath: '/repair/iphone-16-pro-max'
      preLoaderRoute: typeof RepairIphone16ProMaxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repair/iphone-15-pro-max': {
      id: '/repair/iphone-15-pro-max'
      path: '/repair/iphone-15-pro-max'
      fullPath: '/repair/iphone-15-pro-max'
      preLoaderRoute: typeof RepairIphone15ProMaxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repair/iphone-14-pro-max': {
      id: '/repair/iphone-14-pro-max'
      path: '/repair/iphone-14-pro-max'
      fullPath: '/repair/iphone-14-pro-max'
      preLoaderRoute: typeof RepairIphone14ProMaxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repair/iphone-13-pro-max': {
      id: '/repair/iphone-13-pro-max'
      path: '/repair/iphone-13-pro-max'
      fullPath: '/repair/iphone-13-pro-max'
      preLoaderRoute: typeof RepairIphone13ProMaxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repair/ipad': {
      id: '/repair/ipad'
      path: '/repair/ipad'
      fullPath: '/repair/ipad'
      preLoaderRoute: typeof RepairIpadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRouteWithChildren,
  BookRepairRoute: BookRepairRoute,
  ContactRoute: ContactRoute,
  LocationsRoute: LocationsRoute,
  ReviewsRoute: ReviewsRoute,
  ServicesRoute: ServicesRoute,
  TransformationsRoute: TransformationsRoute,
  WarrantyRoute: WarrantyRoute,
  RepairIpadRoute: RepairIpadRoute,
  RepairIphone13ProMaxRoute: RepairIphone13ProMaxRoute,
  RepairIphone14ProMaxRoute: RepairIphone14ProMaxRoute,
  RepairIphone15ProMaxRoute: RepairIphone15ProMaxRoute,
  RepairIphone16ProMaxRoute: RepairIphone16ProMaxRoute,
  RepairMacbookRoute: RepairMacbookRoute,
  RepairSamsungRoute: RepairSamsungRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
